<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LpjSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('lpj')->insert([
            [
                'id' => 1,
                'parent_id' => null,
                'icon' => 'public\\assets2\\media\\misc\\bidang\\bank.png',
                'nama_program' => 'Mobilisasi Sumberdaya',
                'nama_kegiatan' => 'Mobilisasi Sumberdaya',
                'volume' => '1',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => '1',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'icon' => '1',
                'nama_program' => 'Hubungan Antar Lembaga',
                'nama_kegiatan' => 'Hubungan Antar Lembaga',
                'volume' => '1',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => '1',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3,
                'parent_id' => null,
                'icon' => '1',
                'nama_program' => 'Kesehatan',
                'nama_kegiatan' => 'Kesehatan',
                'volume' => '1',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => '1',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4,
                'parent_id' => null,
                'icon' => null,
                'nama_program' => 'Organisasi',
                'nama_kegiatan' => 'Organisasi',
                'volume' => '1',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => '1',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'parent_id' => null,
                'icon' => 'Pembinaan Hukum Olahraga',
                'nama_program' => 'Pembinaan Hukum Olahraga',
                'nama_kegiatan' => 'Pembinaan Hukum Olahraga',
                'volume' => 'tes',
                'jumlah_harga_satuan' => 2,
                'jumlah_harga' => 2,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Pembinaan Hukum Olahraga',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'icon' => 'Pembinaan Prestasi',
                'nama_program' => 'Pembinaan Prestasi',
                'nama_kegiatan' => 'Pembinaan Prestasi',
                'volume' => 'Pembinaan Prestasi',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Pembinaan Prestasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 7,
                'parent_id' => null,
                'icon' => 'Sport Science & IPTEK',
                'nama_program' => 'Sport Science & IPTEK',
                'nama_kegiatan' => 'Sport Science & IPTEK',
                'volume' => 'Sport Science & IPTEK',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Sport Science & IPTEK',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 8,
                'parent_id' => null,
                'icon' => 'Perencanaan Program dan Anggaran',
                'nama_program' => 'Perencanaan Program dan Anggaran',
                'nama_kegiatan' => 'Perencanaan Program dan Anggaran',
                'volume' => 'Perencanaan Program dan Anggaran',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Perencanaan Program dan Anggaran',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'parent_id' => 6,
                'icon' => 'Cabor Terukur',
                'nama_program' => 'Cabor Terukur',
                'nama_kegiatan' => 'Cabor Terukur',
                'volume' => 'Cabor Terukur',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Cabor Terukur',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 10,
                'parent_id' => 6,
                'icon' => 'Cabor Akurasi',
                'nama_program' => 'Cabor Akurasi',
                'nama_kegiatan' => 'Cabor Akurasi',
                'volume' => 'Cabor Akurasi',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Cabor Akurasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'parent_id' => 6,
                'icon' => 'Cabor Permainan',
                'nama_program' => 'Cabor Permainan',
                'nama_kegiatan' => 'Cabor Permainan',
                'volume' => 'Cabor Permainan',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Cabor Permainan',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'parent_id' => 6,
                'icon' => 'Cabor Beladiri',
                'nama_program' => 'Cabor Beladiri',
                'nama_kegiatan' => 'Cabor Beladiri',
                'volume' => 'Cabor Beladiri',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Cabor Beladiri',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'parent_id' => 9,
                'icon' => 'Akuatik - Renang',
                'nama_program' => 'Akuatik - Renang',
                'nama_kegiatan' => 'Akuatik - Renang',
                'volume' => 'Akuatik - Renang',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Akuatik - Renang',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'parent_id' => 9,
                'icon' => 'FAJI - Arung Jeram',
                'nama_program' => 'FAJI - Arung Jeram',
                'nama_kegiatan' => 'FAJI - Arung Jeram',
                'volume' => 'FAJI - Arung Jeram',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'FAJI - Arung Jeram',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'parent_id' => 9,
                'icon' => 'FPTI - Panjat Tebing',
                'nama_program' => 'FPTI - Panjat Tebing',
                'nama_kegiatan' => 'FPTI - Panjat Tebing',
                'volume' => 'FPTI - Panjat Tebing',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'FPTI - Panjat Tebing',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 16,
                'parent_id' => 9,
                'icon' => 'IMI - Balap Motor',
                'nama_program' => 'IMI - Balap Motor',
                'nama_kegiatan' => 'IMI - Balap Motor',
                'volume' => 'IMI - Balap Motor',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'IMI - Balap Motor',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 17,
                'parent_id' => 9,
                'icon' => 'ISSI - Balap Motor',
                'nama_program' => 'ISSI - Balap Motor',
                'nama_kegiatan' => 'ISSI - Balap Motor',
                'volume' => 'ISSI - Balap Motor',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'ISSI - Balap Motor',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 18,
                'parent_id' => 9,
                'icon' => 'PABERSI - Angkat Berat',
                'nama_program' => 'PABERSI - Angkat Berat',
                'nama_kegiatan' => 'PABERSI - Angkat Berat',
                'volume' => 'PABERSI - Angkat Berat',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'PABERSI - Angkat Berat',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 19,
                'parent_id' => 9,
                'icon' => 'PARSI - Angkat Besi',
                'nama_program' => 'PARSI - Angkat Besi ',
                'nama_kegiatan' => 'PARSI - Angkat Besi ',
                'volume' => 'PARSI - Angkat Besi ',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'PARSI - Angkat Besi ',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 20,
                'parent_id' => 9,
                'icon' => 'PASI - Atletik',
                'nama_program' => 'PASI - Atletik',
                'nama_kegiatan' => 'PASI - Atletik',
                'volume' => 'PASI - Atletik',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'PASI - Atletik',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'parent_id' => 9,
                'icon' => 'PORSEROSI - Sepatu Roda',
                'nama_program' => 'PORSEROSI - Sepatu Roda',
                'nama_kegiatan' => 'PORSEROSI - Sepatu Roda',
                'volume' => 'PORSEROSI - Sepatu Roda',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'PORSEROSI - Sepatu Roda',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'parent_id' => 9,
                'icon' => 'Posisi - Dayung',
                'nama_program' => 'Posisi - Dayung ',
                'nama_kegiatan' => 'Posisi - Dayung ',
                'volume' => 'Posisi - Dayung ',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => '1',
                'foto_jurnal' => '1',
                'keterangan_tambahan' => 'Posisi - Dayung ',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'ESI - Esports ',
                'nama_kegiatan' => 'ESI - Esports ',
                'volume' => 'ESI - Esports ',
                'jumlah_harga_satuan' => 10,
                'jumlah_harga' => 122,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'FASI - Aeromodeling',
                'nama_kegiatan' => 'FASI - Aeromodeling',
                'volume' => 'FASI - Aeromodeling',
                'jumlah_harga_satuan' => 12,
                'jumlah_harga' => 12,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 25,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'FTI - Triathlon',
                'nama_kegiatan' => 'FTI - Triathlon',
                'volume' => 'FTI - Triathlon',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 26,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'IODI - Dansa',
                'nama_kegiatan' => 'IODI - Dansa',
                'volume' => 'IODI - Dansa',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 27,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'PBFI - Binaraga',
                'nama_kegiatan' => 'PBFI - Binaraga',
                'volume' => 'PBFI - Binaraga',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 28,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'PERBAKIN - Menembak ',
                'nama_kegiatan' => 'PERBAKIN - Menembak ',
                'volume' => 'PERBAKIN - Menembak ',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 29,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'PERPANI - Panahan ',
                'nama_kegiatan' => 'PERPANI - Panahan ',
                'volume' => 'PERPANI - Panahan ',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 30,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'PERSANI - Senam',
                'nama_kegiatan' => 'PERSANI - Senam',
                'volume' => 'PERSANI - Senam',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 31,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'PGI - Golf ',
                'nama_kegiatan' => 'PGI - Golf ',
                'volume' => 'PGI - Golf ',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 32,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'POBSI - Biliar',
                'nama_kegiatan' => 'POBSI - Biliar',
                'volume' => 'POBSI - Biliar',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 33,
                'parent_id' => 10,
                'icon' => null,
                'nama_program' => 'PORDASI - Berkuda',
                'nama_kegiatan' => 'PORDASI - Berkuda',
                'volume' => 'PORDASI - Berkuda',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 34,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'PSSI - Sepak Bola',
                'nama_kegiatan' => 'PSSI - Sepak Bola',
                'volume' => 'PSSI - Sepak Bola',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 35,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'PERBASI - Basket',
                'nama_kegiatan' => 'PERBASI - Basket',
                'volume' => 'PERBASI - Basket',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 36,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'PELTI - Tenis Lapangan',
                'nama_kegiatan' => 'PELTI - Tenis Lapangan',
                'volume' => 'PELTI - Tenis Lapangan',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 37,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'PSTI - Sepak Takraw',
                'nama_kegiatan' => 'PSTI - Sepak Takraw',
                'volume' => 'PSTI - Sepak Takraw',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 38,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'PTMSI - Tenis Meja',
                'nama_kegiatan' => 'PTMSI - Tenis Meja',
                'volume' => 'PTMSI - Tenis Meja',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 39,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'PBVSI - Pasir & Indoor',
                'nama_kegiatan' => 'PBVSI - Pasir & Indoor',
                'volume' => 'PBVSI - Pasir & Indoor',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 40,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'PBSI - Bulutangkis',
                'nama_kegiatan' => 'PBSI - Bulutangkis',
                'volume' => 'PBSI - Bulutangkis',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 41,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'PERCASI - Catur',
                'nama_kegiatan' => 'PERCASI - Catur',
                'volume' => 'PERCASI - Catur',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 42,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'GABSI - Bridge',
                'nama_kegiatan' => 'GABSI - Bridge',
                'volume' => 'GABSI - Bridge',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 43,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'PDBI - Drumband',
                'nama_kegiatan' => 'PDBI - Drumband',
                'volume' => 'PDBI - Drumband',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 44,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'ABTI - Bola Tangan',
                'nama_kegiatan' => 'ABTI - Bola Tangan',
                'volume' => 'ABTI - Bola Tangan',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 45,
                'parent_id' => 11,
                'icon' => null,
                'nama_program' => 'AFKAB - Futsal',
                'nama_kegiatan' => 'AFKAB - Futsal',
                'volume' => 'AFKAB - Futsal',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 46,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'PGSI - Gulat',
                'nama_kegiatan' => 'PGSI - GulatPGSI - Gulat',
                'volume' => 'PGSI - Gulat',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 47,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'PERTINA - Tinju',
                'nama_kegiatan' => 'PERTINA - Tinju',
                'volume' => 'PERTINA - Tinju',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 48,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'IPSI - Pencak Silat',
                'nama_kegiatan' => 'IPSI - Pencak Silat',
                'volume' => 'IPSI - Pencak Silat',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 49,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'FORKI - Karate',
                'nama_kegiatan' => 'FORKI - Karate',
                'volume' => 'FORKI - Karate',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 50,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'PERKEMI - Kempo',
                'nama_kegiatan' => 'PERKEMI - Kempo',
                'volume' => 'PERKEMI - Kempo',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 51,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'PJSI - Judo',
                'nama_kegiatan' => 'PJSI - Judo',
                'volume' => 'PJSI - Judo',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 52,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'IKASI - Anggar',
                'nama_kegiatan' => 'IKASI - Anggar',
                'volume' => 'IKASI - Anggar',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 53,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'TI - Taekwondo',
                'nama_kegiatan' => 'TI - Taekwondo',
                'volume' => 'TI - Taekwondo',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 54,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'MI - Muaythai',
                'nama_kegiatan' => 'MI - Muaythai',
                'volume' => 'MI - Muaythai',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 55,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'FERKUSHI - Kuras',
                'nama_kegiatan' => 'FERKUSHI - Kuras',
                'volume' => 'FERKUSHI - Kuras',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 56,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'IBCA MMA - Martial Art',
                'nama_kegiatan' => 'IBCA MMA - Martial Art',
                'volume' => 'IBCA MMA - Martial Art',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 57,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'PERSAMBI - Sambo',
                'nama_kegiatan' => 'PERSAMBI - Sambo',
                'volume' => 'PERSAMBI - Sambo',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 58,
                'parent_id' => 12,
                'icon' => null,
                'nama_program' => 'KBI - Kick Boxing',
                'nama_kegiatan' => 'KBI - Kick Boxing',
                'volume' => 'KBI - Kick Boxing',
                'jumlah_harga_satuan' => 1,
                'jumlah_harga' => 1,
                'dokumen_lpj' => null,
                'foto_jurnal' => null,
                'keterangan_tambahan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
